### ISSUE TITLE
Fix event-stream dep

### ISSUE THREAD

**Issue by PWKad** [mllrsohn/gulp-protractor#139]
https://github.com/dominictarr/event-stream/issues/116

**Comment by sirudog** [comment]
@steffenmllr Would it be possible to bump the version and publish to npmjs.org asap? The lastest published one still references event-stream@3.3.5
Many thanks in advance

**Comment by steffenmllr** [comment]
I've published `4.1.1` and deprecated everything before it. Since I don't really maintain this repository anymore hope this is fine with @RobbinHabermehl @mattfritz @rahulmr 

Btw. I would be fine to transfer the ownership of this repository if someone is interested. 

Looking at the commit history it seems like @rahulmr might be a good choice if you are interested :)

**Comment by PWKad** [comment]
Thank you for the quick response, we are currently phasing out the lib in projects that I contribute to but I think this will help with legacy systems as well that have had the dependency for a long time.  It's likely that it is simply a dev dep so not really affected but it's better to be proactive. 

Thanks again!
