### ISSUE TITLE
ignoreSynchronization is required

### ISSUE THREAD

**Issue by Deminetix** [mllrsohn/gulp-protractor#31]
Is anyone else having getting the error:

    Error: Error while waiting for Protractor to sync with the page: {}

I have a minimal angular project and a basic test

```
describe('Home', function(){

    beforeEach(function(){
        browser.get('http://localhost:3020/#/home');
    });

    it('should have a title element', function(){
        expect($('h1').isPresent()).toBe(true);
    });

});
````

Which gives me that error. I can fix it by adding `ignoreSynchronization` to the beforeEach but that shouldnt be required in every test file.

````
    beforeEach(function(){
        browser.ignoreSynchronization = true;
        browser.get('http://localhost:3020/#/home');
    });
````

**Comment by mattfritz** [comment]
This shouldn't be an issue with the plugin. Either the angular is not loading, the app continuously polls (see https://github.com/angular/protractor/blob/master/docs/timeouts.md) or there may be a redirect that protractor cannot follow.

I know this issue is old, but there may be resources here https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions
