### ISSUE TITLE
Use files from protractor.conf.js

### ISSUE THREAD

**Issue by dhoko** [mllrsohn/gulp-protractor#48]
How can I use files from my config file and not from the glob in gulp.src ?

**Comment by tkrotoff** [comment]
+1, good question
I would like to support protractor via gulp and also without gulp (just protractor command line itself) without the need to specify 2 times the spec files.

**Comment by apetherick** [comment]
Any progress on this?

**Comment by iamryandrake** [comment]
+1

**Comment by mattfritz** [comment]
Gulp plugins require a file stream, so not passing a file or a glob is not an option. If you want to store everything in a `protractor.conf` file, there is no need to utilize gulp streams so you can use [this alternative](https://github.com/mllrsohn/gulp-protractor/blob/master/README.md#running-protractor-without-a-plugin) to write a gulp task instead of a plugin.


To configure test files (from the [angular/protractor docs](https://github.com/angular/protractor/blob/master/docs/referenceConf.js)):

```js
// Spec patterns are relative to the location of this config.
  specs: [
    'spec/*_spec.js'
  ],

  // Patterns to exclude.
  exclude: [],

  // Alternatively, suites may be used. When run without a command line
  // parameter, all suites will run. If run with --suite=smoke or
  // --suite=smoke,full only the patterns matched by the specified suites will
  // run.
  suites: {
    smoke: 'spec/smoketests/*.js',
    full: 'spec/*.js'
  }
```
