### ISSUE TITLE
Gulp Protractor tests passing when it should fail

### ISSUE THREAD

**Issue by karneaud** [mllrsohn/gulp-protractor#99]
I am using your plugin to do angularjs unit testing and refer to this [thread](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/177#issuecomment-196044537l)

**Comment by mattfritz** [comment]
This should be fixed with the latest release, which updates Protractor to `v3.2.2`. There are several side effects when Protractor is installed as a project dependency instead of just using the version included with gulp-protractor, so removing `protractor` from `devDependencies` in your `package.json` is recommended. 

https://github.com/mllrsohn/gulp-protractor/issues/101 will allow users to update Protractor without depending on gulp-protractor and should help with upgrades and problems like this. Let me know if removing the dependency and updating gulp-protractor does not solve the issue and I'll reopen this issue.
